array_layout = "Block"
fn_brace_style = "SameLineWhere"
fn_call_style = "Block"
fn_return_indent = "WithArgs"
generics_indent = "Block"
hard_tabs = true
item_brace_style = "PreferSameLine"
max_width = 170
merge_derives = true
merge_empty_match_arm = true
merge_impls = true
merge_imports = true
merge_trait_impls = true
merge_tuple_index = true
newline_style = "Windows"
reorder_imports = true
spaces_within_angle_brackets = false
spaces_within_parens = false
spaces_within_square_brackets = false
tab_spaces = 3
where_layout = "Horizontal"
where_pred_indent = "Block"
where_style = "Rfc"
